=== ilerviraragavane/DevooProject/opti_fret_courly/src/test/demandes/demandes.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT  JourneeType (Entrepot,PlagesHoraires)>
<!ELEMENT Entrepot EMPTY>

<!ATTLIST Entrepot
	adresse CDATA #REQUIRED>

<!ELEMENT  PlagesHoraires (Plage)*>
<!ELEMENT  Plage (Livraisons)>
<!ATTLIST Plage 
	heureDebut CDATA #REQUIRED
	heureFin CDATA #REQUIRED>
	
<!ELEMENT  Livraisons (Livraison)*>
<!ELEMENT Livraison EMPTY>
<!ATTLIST Livraison	
	id CDATA #REQUIRED
	client CDATA #REQUIRED
	adresse CDATA #REQUIRED>

=== ilerviraragavane/DevooProject/opti_fret_courly/src/test/demandes/demandes17.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE JourneeType SYSTEM "demandes.dtd">
<JourneeType>
    <Entrepot adresse="1"/>
    <PlagesHoraires>
        <Plage heureDebut="8:0:0" heureFin="9:30:0">
            <Livraisons>
                <Livraison id="1" client="329" adresse="2"/>
                <Livraison id="2" client="41" adresse="3"/>
            </Livraisons>
        </Plage>
      <Plage heureDebut="10:0:0" heureFin="10:30:0">
            <Livraisons>
              
            </Livraisons>
        </Plage>
    </PlagesHoraires>
</JourneeType>
